apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: booking-service-deployment
  labels:
    app: booking-service
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
        branch: release
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: In
                values:
                - default
      containers:
      - name: booking-service
        image: 644506256020.dkr.ecr.ca-central-1.amazonaws.com/blerxprepo:latest-dev
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 1000Mi    
          limits:
            cpu: 1
            memory: 2000Mi
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
        env:
          - name: PORT
            value: "80"
          - name: DEPLOY_DATE
            value: "{{DEPLOY_DATE}}"
---
kind: Service
apiVersion: v1
metadata:
    namespace: default
    name: booking-service
spec:
    selector:
      app: booking-service
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
