apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service-deployment
  labels:
    app: hotel-service
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
        branch: master
    spec:
      containers:
      - name: hotel-service
        image: 644506256020.dkr.ecr.ca-central-1.amazonaws.com/blerxprepo:latest-dev
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi    
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
        env:
          - name: PORT
            value: "80"
          - name: DEPLOY_DATE
            value: "{{DEPLOY_DATE}}"
---
kind: Service
apiVersion: v1
metadata:
    namespace: default
    name: hotel-service
spec:
    selector:
      app: hotel-service
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
